{{- if (include "newrelic-k8s-metrics-adapter.areValuesValid" .) }}
{{- if .Values.personalAPIKey }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic.common.naming.fullname" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "newrelic-k8s-metrics-adapter.customSecretPersonalApiKeyKey" . }}: {{ .Values.personalAPIKey | required "personalAPIKey must be set" | quote }}
{{- end }}
{{- end }}
